name: nivel_mamado
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  flutter_riverpod: ^2.5.1
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.2.1+1
  font_awesome_flutter: ^10.7.0
  lucide_flutter: ^0.563.0
  google_fonts: ^6.2.1
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0
  confetti: ^0.7.0
  flutter_animate: ^4.5.0
  vibration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
